version: 2.1 # バージョン指定

executors:
  default:
    working_directory: ~/webapp
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: "root"
          DB_PASSWORD: ""
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Update bundler # bundlerのバージョン２へのアップデート
          command: gem update bundler

      - run:
          name: Which bundler? # バージョン確認
          command: bundle -v

      - restore_cache: # キャッシュを読み込む
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      - save_cache: # キャッシュを保存する
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # 以下はRails6でWebpackerを使う場合は必須
      - restore_cache:
          keys:
            - yarn-cache-v1-{{ checksum "yarn.lock" }}
            - yarn-cache-v1-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  test:
    executor: default
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 90s

      - run:
          name: Use specific database.yml # CircleCI用のデータベース設定を使う
          command: mv config/database.yml.ci config/database.yml

      - run:
          name: Database setup
          command: |
            bin/rails db:create
            bin/rails db:schema:load --trace

      - run: # 普通のテストとシステムテストを実行する
          name: Rails Test
          command: |
            bin/rails test  
            bin/rails test:system

workflows:
  build_and_test:
    jobs:
      - test
