version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          RAILS_ENV: test
          DATABASE_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: soccer_app_test
    working_directory: ~/soccer_app
    steps:
      - checkout
      - run:
          name: "bundle install"
          command: bundle install
      # MySQLと接続できるまで待ちます
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: "initialize DB"
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2
  workflows:
    jobs:
      - test
