version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/soccer_app
    steps:
      - checkout
      - run:
          name: Run test
          command: bundle exec rspec spec/models/like_spec.rb

workflows:
  version: 2
  workflows:
    jobs:
      - test
