name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  spec:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
      - run: docker-compose run --rm web yarn install --cache-files
      - run: docker-compose run --rm web rails webpacker:compile
      - run: docker-compose run --rm web rails webpacker:compile RAILS_ENV=test
      - run: docker-compose run --rm web rails db:create
      - run: docker-compose run --rm web rails db:migrate
      - run: docker-compose run --rm web bundle exec rspec
